version: '2'

services:
    application:
        container_name: lws_application
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: lws_workspace
        restart: always
        image: thangtd90/laravel-workspace-unoconv
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: lws_php-fpm
        restart: always
        image: thangtd90/php-fpm-unoconv
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace
    nginx:
        container_name: lws_nginx
        restart: always
        image: framgia/laravel-nginx
        volumes_from:
            - data
            - logs
            - application
        ports:
            - "8000:80"
        links:
            - php-fpm
    data:
        container_name: lws_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    data_test:
        container_name: lws_data_test
        image: debian
        volumes:
            - .docker/mysql_test:/var/lib/mysql
            - .docker/data_test:/data
    logs:
        container_name: lws_logs
        image: debian
        volumes:
            - .docker/logs/nginx:/var/log/nginx
    mysql:
        container_name: lws_mysql
        restart: always
        image: mysql
        volumes_from:
            - data
            - logs
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    mysql_test:
        container_name: lws_mysql_test
        restart: always
        image: mysql
        volumes_from:
            - data_test
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: homestead_test
            MYSQL_USER: homestead_test
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    redis:
        container_name: lws_redis
        restart: always
        image: redis
        expose:
            - "6379"
        volumes_from:
            - data
